/**
 * Draw + DrawFrame
 */
package ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
//import javafx.scene.paint.Color;
//import javax.swing.JScrollPane;

public class Main extends javax.swing.JFrame {

    private ToolBar toolBar;
    private CoordinateBar coordinateBar;
    private ColorChooser colorChooser;
    private Paint inkPaint;
    private JScrollPane sp;

    public Main() {
        initComponents();
        setLayout(new BorderLayout());
        setExtendedState(JFrame.MAXIMIZED_BOTH); //set fullscreen

        // create coordianate bar
        coordinateBar = new CoordinateBar();
        
        // construct layout manager
        Content content = new Content();
        inkPaint = new Paint(this);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int inkPanelWidth = dim.width - 150;
        int inkPanelHeight = dim.height - 160;
        sp = new JScrollPane();
        sp.setLocation(10, 10);
        sp.setViewportView(inkPaint);
        sp.setSize(inkPanelWidth, inkPanelHeight);
        sp.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        sp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        content.add(sp);

        // create tool bar
        toolBar = new ToolBar(this);

        // create color chooser
        colorChooser = new ColorChooser();

        // set components
        add(colorChooser, BorderLayout.PAGE_START);
        add(content);
        add(coordinateBar, BorderLayout.PAGE_END);
        add(toolBar, BorderLayout.WEST);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    // get component
    public Paint getInkPanel() {
        return this.inkPaint;
    }

    public JScrollPane getSP() {
        return this.sp;
    }

    public CoordinateBar getCoordinateBar() {
        return this.coordinateBar;
    }
}
